# language
language: objective-c
osx_image: xcode9.2
rvm:
- 2.2         #see before_install for getting RVM stable.

env:
# - TRAVIS_TAG="Deploy-2019.2.6f1" # This sets the tag on a build
  - PROJECT_NAME="SeasonShift"
  - UNITY_PROJECT_PATH="Game"
  - DEPLOY_UNITYPACKAGE="path set in deploy script"


cache:
  directories:
    - $UNITY_DOWNLOAD_CACHE

    
before_install:
- chmod a+x ./buildScripts/*.sh

install:
- cat /etc/hosts
- pwd
- ./buildScripts/install-unity.sh

script:
- ./buildScripts/build.sh
- ./buildScripts/run-tests.sh

after_success:
- ./buildScripts/export-unity-package.sh

before_deploy:
- DEPLOY_UNITYPACKAGE="$(ls -a release/*.zip | head -n 1)"

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: $DEPLOY_UNITYPACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true 